name: node.js
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node: [14.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{matrix.node}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - name: Install windows build tools
        if: contains(matrix.os, 'windows')
        run: npm install --global windows-build-tools
      - name: Install & Build
        run: npm install
